-- Download history tracking

CREATE TABLE IF NOT EXISTS public.downloads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  frame_name text not null
);

ALTER TABLE public.downloads enable row level security;

CREATE POLICY "Users can view their own downloads"
  ON public.downloads for select
  using ( auth.uid() = user_id );

CREATE POLICY "Users can insert their own downloads"
  ON public.downloads for insert
  with check ( auth.uid() = user_id );