-- Supabase migration: initial schema for FrameMe

-- 1. Create the frames table
create table public.frames (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  src text not null,
  user_id uuid references auth.users not null,
  is_public boolean default true not null
);

-- 2. Enable Row Level Security
alter table public.frames enable row level security;

-- 3. RLS Policies
-- Anyone can read public frames
create policy "Public frames are viewable by everyone"
  on public.frames for select
  using ( is_public = true );

-- Authenticated users can insert their own frames
create policy "Users can insert their own frames"
  on public.frames for insert
  with check ( auth.uid() = user_id );

-- Users can update their own frames
create policy "Users can update their own frames"
  on public.frames for update
  using ( auth.uid() = user_id );

-- Users can delete their own frames
create policy "Users can delete their own frames"
  on public.frames for delete
  using ( auth.uid() = user_id );

-- 4. Storage bucket setup (requires bucket named 'frames' to exist)
-- Note: Storage buckets must be created via Supabase Dashboard or CLI
-- The policies below assume a bucket named 'frames' exists

-- Allow public uploads to 'frames' bucket (authenticated users)
insert into storage.buckets (id, name, public)
values ('frames', 'frames', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Public URLs are accessible"
  on storage.objects for select
  using ( bucket_id = 'frames' );

create policy "Users can upload to frames bucket"
  on storage.objects for insert
  with check (
    bucket_id = 'frames'
    and auth.uid() is not null
  );

create policy "Users can update their own uploads"
  on storage.objects for update
  using (
    bucket_id = 'frames'
    and auth.uid() = owner
  );

create policy "Users can delete their own uploads"
  on storage.objects for delete
  using (
    bucket_id = 'frames'
    and auth.uid() = owner
  );